<?php 
/*
Plugin Name: Daystatus
Plugin URI: https://github.com/daystatus/wordpress-daystatus
Description: WordPress version health check for daystatus.com
Version: 0.0.1
Author: Aphichat Panjamanee
Author URI: https://github.com/daystatus
Text Domain: d
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}